methylpiper_logs_path: "/Cluster_Filespace/Marioni_Group/Yipeng/prediction-pipelines/rtfs_20k/gp_hosp_40_60/scripts_20230221/results_gp_smr/methylpiper_logs/"
dnam_data_path: "/Local_Scratch/Yipeng/"
baseline_phenotypes_path: "/Cluster_Filespace/Marioni_Group/GS/GS_dataset/"
raw_dnam_data_path: "/Scratch_Area/Ola/"
continuous_traits_methylpiper_logs_path: "/Cluster_Filespace/Marioni_Group/Yipeng/prediction-pipelines/rtfs_20k/results/continuous_traits_w4_filtered_by_family/"
continuous_traits_data_path: "~/rtfs_20k/"
epic_annotation_file_path: "/Cluster_Filespace/Marioni_Group/Yipeng/data/GS/IHD_pipeline/EPIC_AnnotationObject_df.rds"
pedigree_file_path: "/Cluster_Filespace/Marioni_Group/Yipeng/prediction-pipelines/incident_diabetes_pipeline/using_methylpiper/src/20k/preprocessing/2022-01-17_pedigree.csv"
t2d_data_path: "/Cluster_Filespace/Marioni_Group/Yipeng/prediction-pipelines/rtfs_20k/gp_hosp_40_60/"
gs_target_file_path: "/Cluster_Filespace/Marioni_Group/Yipeng/prediction-pipelines/rtfs_20k/target_files/"
body_file_path: "/Cluster_Filespace/Marioni_Group/Yipeng/data/GS/"
disease_table_file_path: "/Cluster_Filespace/Marioni_Group/Yipeng/prediction-pipelines/incident_diabetes_pipeline/data/"
bootstrap_results_path: "/Cluster_Filespace/Marioni_Group/Yipeng/prediction-pipelines/rtfs_20k/gp_hosp_40_60/scripts_20230221/results_gp_smr/"
prs_file_path: "/Cluster_Filespace/Marioni_Group/Yipeng/INTERVENE/flagship/prs_output/"
